---
# === Configure Main function === #
category_train: ./Data/Training_truth/
category_valid: ./Data/Valid_truth/
category_test: ./Data/Testing_real_data/  
category_mask: ./Data/   
model_name: Decoder
result_dir: Result
result_model: Model-Config
result_data: Testing-Result
model_filename: 
GPU: 0

# === Configure Model Handler === #
# Data Assignment
num_width: 660
num_height: 660
num_channel: 24
batch_size: 5
# Model training Controler
epochs: 300
learning_rate: 0.01
lr_decay: 0.7
lr_decay_epoch: 1
lr_decay_interval: 20 
loss_func: RMSE
max_grad_norm: 5.0


